all:
	g++ -g format.cpp -o format
	g++ -g concat.cpp -o concat
	g++ -g numconv.cpp -o numconv
	g++ -g callother.cpp -o callother
	g++ -g textfileio.cpp -o textfileio
	g++ -g vectorintro.cpp -o vecintro
	g++ -g binary.cpp -o binary

clean:
	rm -f format
	rm -f concat
	rm -f numconv
	rm -f callother
	rm -f textfileio
	rm -f vecintro
	rm -f binary
	rm -f *.2
	rm -f *~
