# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cucb_gl', [dirname(__file__)])
        except ImportError:
            import _cucb_gl
            return _cucb_gl
        if fp is not None:
            try:
                _mod = imp.load_module('_cucb_gl', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cucb_gl = swig_import_helper()
    del swig_import_helper
else:
    import _cucb_gl
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class DPoint(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DPoint, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DPoint, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _cucb_gl.DPoint_x_set
    __swig_getmethods__["x"] = _cucb_gl.DPoint_x_get
    if _newclass:x = _swig_property(_cucb_gl.DPoint_x_get, _cucb_gl.DPoint_x_set)
    __swig_setmethods__["y"] = _cucb_gl.DPoint_y_set
    __swig_getmethods__["y"] = _cucb_gl.DPoint_y_get
    if _newclass:y = _swig_property(_cucb_gl.DPoint_y_get, _cucb_gl.DPoint_y_set)
    def __init__(self): 
        this = _cucb_gl.new_DPoint()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cucb_gl.delete_DPoint
    __del__ = lambda self : None;
DPoint_swigregister = _cucb_gl.DPoint_swigregister
DPoint_swigregister(DPoint)


def points_create(*args):
  return _cucb_gl.points_create(*args)
points_create = _cucb_gl.points_create

def points_get_by_index(*args):
  return _cucb_gl.points_get_by_index(*args)
points_get_by_index = _cucb_gl.points_get_by_index

def points_set_by_index(*args):
  return _cucb_gl.points_set_by_index(*args)
points_set_by_index = _cucb_gl.points_set_by_index

def points_destroy(*args):
  return _cucb_gl.points_destroy(*args)
points_destroy = _cucb_gl.points_destroy

def bezier_spline(*args):
  return _cucb_gl.bezier_spline(*args)
bezier_spline = _cucb_gl.bezier_spline

def quadratic_b_spline_interp(*args):
  return _cucb_gl.quadratic_b_spline_interp(*args)
quadratic_b_spline_interp = _cucb_gl.quadratic_b_spline_interp

def cubic_b_spline_interp(*args):
  return _cucb_gl.cubic_b_spline_interp(*args)
cubic_b_spline_interp = _cucb_gl.cubic_b_spline_interp
# This file is compatible with both classic and new-style classes.


