all:
	g++ -g format.cpp -o format
	g++ -g concat.cpp -o concat
	g++ -g numconv.cpp -o numconv
	g++ -g callother.cpp -o callother

clean:
	rm -f format
	rm -f concat
	rm -f numconv
	rm -f callother
	rm -f *~
